title: "Imeji - A lightweight research data repository"
description: imeji a free and open source web application to manage and publish any research data
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
