name: Build and test
on: [push, workflow_dispatch]
jobs:
  buid_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run the Maven build
        run: mvn clean package -P env-testing

